spring:
  application:
    name: currency-converter-back
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

cb:
  url: ${CB_URL}
  base-currency:
    char-code: RUB
    name: Российский рубль

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration_minutes: ${JWT_EXPIRATION_MINUTES}
  admin:
    username: ${ADMIN_USERNAME}
    password: ${ADMIN_PASSWORD}

server:
  port: ${SERVER_PORT}